public enum Page {
    EXIT, LOGIN_PAGE, MAIN_MENU,

    LIBRARIAN_MENU,
    LIBRARIAN_ACCEPT_ORDER,     LIBRARIAN_ADD_BOOK,
    LIBRARIAN_ADD_READER,       LIBRARIAN_BLOCK_READER,
    LIBRARIAN_BOOK_ORDER_LIST,  LIBRARIAN_BOOK_RENT_LIST,
    LIBRARIAN_DECLINE_ORDER,    LIBRARIAN_REMOVE_BOOK,
    LIBRARIAN_REMOVE_READER,    LIBRARIAN_SEARCH_BOOK,
    LIBRARIAN_SEARCH_READER,    LIBRARIAN_UNBLOCK_READER,
    LIBRARIAN_VIEW_ALL_BOOKS,   LIBRARIAN_VIEW_ALL_READERS,


    READER_MENU,
    READER_REMOVE_BOOK,         READER_RENT_BOOK,
    READER_REQUEST_ORDER_BOOK,  READER_SEARCH_BOOK,
    READER_VIEW_ALL_BOOKS,      READER_VIEW_ORDER_BOOKS,
    READER_VIEW_OWNED_BOOKS,    READER_VIEW_RENT_BOOKS,

}

// Pages and Actions