public enum Page {
    EXIT,MAIN_MENU,LOGIN_PAGE,

    LIBRARIAN_MENU,
    LIBRARIAN_ADD_READER,LIBRARIAN_REMOVE_READER,
    LIBRARIAN_ADD_BOOK,LIBRARIAN_REMOVE_BOOK,
    LIBRARIAN_SEARCH_BOOK,LIBRARIAN_SEARCH_READER,
    LIBRARIAN_BOOK_ORDER_LIST,LIBRARIAN_BOOK_RENT_LIST,
    LIBRARIAN_VIEW_ALL_BOOKS,LIBRARIAN_VIEW_ALL_READERS,
    LIBRARIAN_ACCEPT_ORDER,LIBRARIAN_DECLINE_ORDER,
    LIBRARIAN_BLOCK_READER,LIBRARIAN_UNBLOCK_READER,

    READER_MENU,
    READER_SEARCH_BOOK,READER_REMOVE_BOOK,
    READER_RENT_BOOK,READER_REQUEST_ORDER_BOOK,
    READER_VIEW_ORDER_BOOKS,READER_VIEW_RENT_BOOKS,
    READER_VIEW_ALL_BOOKS,READER_VIEW_OWNED_BOOKS
}

// Pages and Actions