
public enum Page {
    EXIT,MAIN_MENU,LOGIN_PAGE,SIGN_UP,

    LIBRARIAN_MENU,
    LIBRARIAN_ADD_READER,LIBRARIAN_REMOVE_READER,
    LIBRARIAN_ADD_BOOK,LIBRARIAN_REMOVE_BOOK,
    LIBRARIAN_SEARCH_BOOK,LIBRARIAN_BOOK_ORDER_LIST,LIBRARIAN_BLOCK_READER,

    READER_MENU,
    READER_ADD_BOOK,READER_REMOVE_BOOK,
    READER_SEARCH_BOOK,READER_RENT_BOOK
}